Use np.frombuffer instead of np.fromstring
This will fix the following execution error:

ValueError: The binary mode of fromstring is removed, use frombuffer instead